const mockArray = [
    {
    "id": 1,
    "type": "Car",
    "brand": "Toyota",
    "model": "Corrola",
    "bodystyle": "sedan",
    "year": 2018,
    "seats": 5,
    "price": 21000,
    "imgURL": "./assets/images/cars/Corolla.jpeg",
    'leaseType': 'normal',
  },
    {
    "id": 2,
    "type": "Car",
    "brand": "Honda",
    "model": "Civic",
    "bodystyle": "hatchback",
    "year": 2019,
    "seats": 5,
    "price": 19100,
    "imgURL": "./assets/images/cars/civic.jpeg",
    'leaseType': 'normal',
  },
    {
    "id": 3,
    "type": "Car",
    "brand": "BMW",
    "model": "3 Series",
    "bodystyle": "sedan",
    "year": 2017,
    "seats": 5,
    "price": 19500,
    "imgURL": "./assets/images/cars/3-series.jpeg",
    'leaseType': 'normal',
  },
    {
    "id": 4,
    "type": "Car",
    "brand": "Audi",
    "model": "A4",
    "bodystyle": "sedan",
    "year": 2018,
    "seats": 5,
    "price": 21000,
    "imgURL": "./assets/images/cars/audi-a4.jpeg",
    'leaseType': 'normal',
  },
    {
    "id": 5,
    "type": "Car",
    "brand": "Volkswagen",
    "model": "Golf",
    "bodystyle": "hatchback",
    "year": 2016,
    "seats": 5,
    "price": 13200,
    "imgURL": "./assets/images/cars/vw-golf.jpeg",
    'leaseType': 'normal',
  },
    {
    "id": 6,
    "type": "Car",
    "brand": "Ford",
    "model": "Focus",
    "bodystyle": "sedan",
    "year": 2017,
    "seats": 5,
    "price": 12800,
    "imgURL": "./assets/images/cars/focus.jpeg",
    'leaseType': 'normal',
  },
    {
    "id": 7,
    "type": "Van",
    "brand": "Ford",
    "model": "Transit",
    "bodystyle": "cargo van",
    "year": 2019,
    "seats": 3,
    "price": 26500,
    "imgURL": "./assets/images/cars/transit.jpeg",
    'leaseType': 'normal',
  },
    {
    "id": 8,
    "type": "Van",
    "brand": "Mercedes-Benz",
    "model": "Sprinter",
    "body style": "high roof van",
    "year": 2018,
    "seats": 3,
    "price": 31000,
    "imgURL": "./assets/images/about-us/superling150h.jpg",
    'leaseType': 'normal',
  },
    {
    "id": 9,
    "type": "Van",
    "brand": "Volkswagen",
    "model": "Transporter T6",
    "bodystyle": "panel van",
    "year": 2017,
    "seats": 3,
    "price": 27500,
    "imgURL": "./assets/images/cars/vw-transporter.jpeg",
    'leaseType': 'normal',
  },
    {
    "id": 10,
    "type": "Van",
    "brand": "Renault",
    "model": "Trafic",
    "bodystyle": "cargo van",
    "year": 2020,
    "seats": 3,
    "price": 22000,
    "imgURL": "./assets/images/cars/trafic.jpeg",
    'leaseType': 'normal',
  },
    {
    "id": 11,
    "type": "Van",
    "brand": "Peugot",
    "model": "Traveller",
    "bodystyle": "passenger van",
    "year": 2019,
    "seats": 8,
    "price": 27000,
    "imgURL": "./assets/images/about-us/superling150h.jpg",
    'leaseType': 'normal',
     // No image exists on the site for this vehicle, should be changed to a 404 error
  },
    {
    "id": 12,
    "type": "Van",
    "brand": "Toyota",
    "model": "Proace Verso",
    "bodystyle": "minivan",
    "year": 2021,
    "seats": 9,
    "price": 29500,
    "imgURL": "./assets/images/cars/proace-standard.jpeg",
    'leaseType': 'normal',
      //There was no verso image on the site, hence the proace standard was used
  },
    {
    "id": 13,
    "type": "Car",
    "brand": "Toyota",
    "model": "Corrola",
    "bodystyle": "sedan",
    "year": 2018,
    "seats": 5,
    "price": 1000,
    "imgURL": "./assets/images/cars/Corolla.jpeg",
    'leaseDuration': 24,
    'leaseType': 'leasing',
  },
    {
    "id": 14,
    "type": "Car",
    "brand": "Honda",
    "model": "Civic",
    "bodystyle": "hatchback",
    "year": 2019,
    "seats": 5,
    "price": 900,
    "imgURL": "./assets/images/cars/civic.jpeg",
    'leaseDuration': 12,
    'leaseType': 'leasing',
  },
    {
    "id": 15,
    "type": "Van",
    "brand": "Renault",
    "model": "Trafic",
    "bodystyle": "cargo van",
    "year": 2020,
    "seats": 3,
    "price": 1300,
    "imgURL": "./assets/images/cars/trafic.jpeg",
    'leaseDuration': 12,
    'leaseType': 'leasing',
  },
    {
    "id": 16,
    "type": "Van",
    "brand": "Volkswagen",
    "model": "Transporter T6",
    "bodystyle": "panel van",
    "year": 2017,
    "seats": 3,
    "price": 1100,
    "imgURL": "./assets/images/cars/vw-transporter.jpeg",
    'leaseDuration': 36,
    'leaseType': 'leasing',
  },
  //leasing vehicles
]

export {mockArray};
