const mockArray = [
  {
    "type": "Car",
    "brand": "Toyota",
    "model": "Corrola",
    "bodystyle": "sedan",
    "year": 2018,
    "seats": 5,
    "price": 21000,
  },
    {
    "type": "Car",
    "brand": "Honda",
    "model": "Civic",
    "bodystyle": "hatchback",
    "year": 2019,
    "seats": 5,
    "price": 19100,
  },
    {
    "type": "Car",
    "brand": "BMW",
    "model": "3 Series",
    "bodystyle": "sedan",
    "year": 2017,
    "seats": 5,
    "price": 19500,
  },
    {
    "type": "Car",
    "brand": "Audi",
    "model": "A4",
    "bodystyle": "sedan",
    "year": 2018,
    "seats": 5,
    "price": 21000,
  },
    {
    "type": "Car",
    "brand": "Volkswagen",
    "model": "Golf",
    "bodystyle": "hatchback",
    "year": 2016,
    "seats": 5,
    "price": 13200,
  },
    {
    "type": "Car",
    "brand": "Ford",
    "model": "Focus",
    "bodystyle": "sedan",
    "year": 2017,
    "seats": 5,
    "price": 12800,
  },
    {
    "type": "Van",
    "brand": "Ford",
    "model": "Transit",
    "bodystyle": "cargo van",
    "year": 2019,
    "seats": 3,
    "price": 26500,
  },
    {
    "type": "Van",
    "brand": "Mercedes-Benz",
    "model": "Sprinter",
    "body style": "high roof van",
    "year": 2018,
    "seats": 3,
    "price": 31000,
  },
    {
    "type": "Van",
    "brand": "Volkswagen",
    "model": "Transporter T6",
    "bodystyle": "panel van",
    "year": 2017,
    "seats": 3,
    "price": 27500,
  },
    {
    "type": "Van",
    "brand": "Renault",
    "model": "Traffic",
    "bodystyle": "cargo van",
    "year": 2020,
    "seats": 3,
    "price": 22000,
  },
    {
    "type": "Van",
    "brand": "Peugot",
    "model": "Traveller",
    "bodystyle": "passenger van",
    "year": 2019,
    "seats": 8,
    "price": 27000,
  },
    {
    "type": "Van",
    "brand": "Toyota",
    "model": "Proace Verso",
    "bodystyle": "minivan",
    "year": 2021,
    "seats": 9,
    "price": 29500,
  },
]
export {mockArray};